name: Setup Chromium Subtree
on:
  workflow_dispatch:  # Manual trigger only
  push:
    branches: [ master ]
    paths: [ '.github/workflows/setup-chromium-subtree.yml' ]

jobs:
  setup-chromium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      
      - name: Add Chromium subtree (using commit hash)
        run: |
          # Get the latest commit hash from Chromium repository
          CHROMIUM_COMMIT=$(git ls-remote https://github.com/RiaanDeWinnaar/chromium.git main | cut -f1)
          echo "Latest Chromium commit: $CHROMIUM_COMMIT"
          
          # Add as subtree using the commit hash directly
          git subtree add --prefix=chromium --squash https://github.com/RiaanDeWinnaar/chromium.git $CHROMIUM_COMMIT
      
      - name: Configure sparse checkout for Chromium
        run: |
          cd chromium
          git config core.sparseCheckout true
          cat > .git/info/sparse-checkout << EOF
          content/browser/webui/
          chrome/browser/ui/webui/
          chrome/common/webui_url_constants.cc
          chrome/common/webui_url_constants.h
          chrome/browser/BUILD.gn
          chrome/browser/chrome_browser_main.cc
          chrome/browser/chrome_browser_main.h
          EOF
          git read-tree -m -u HEAD
      
      - name: Commit Chromium subtree setup
        run: |
          git add chromium/
          git commit -m "Add Chromium fork as git subtree with selective components
          
          - Added Chromium fork as subtree using commit hash approach
          - Configured sparse checkout for WebUI components only
          - Includes content/browser/webui/ and chrome/browser/ui/webui/
          - Ready for chrome://ai-browser/ protocol implementation"
      
      - name: Push changes
        run: git push origin master